name:                union-color
version:             0.1.4.0
github:              "YoshikuniJujo/union-color"
license:             BSD3
author:              "Yoshikuni Jujo"
maintainer:          "yoshikuni.jujo.pc@gmail.com"
copyright:           "2022 Yoshikuni Jujo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Unify verious color formats
category:            data, graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/union-color#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  union-color-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - union-color
